server.port: 8090
spring.h2.console.enabled: true
    
logging:
  pattern:
     console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
     file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
     root: INFO
     org.springframework.web: DEBUG
     com.peraton.air: DEBUG
application.env: qa
cloud:
  aws:
    stack.auto: false
spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
     