apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
  pull_request:
    branches:
      - "*"
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  build:
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1
      - name: Setup git credentials
        uses: cloudbees-io/configure-git-global-credentials@v1
        with:
          repositories: calculi-corp/dsl-engine-cli, cloudbees-io/workflow-advisor
      - id: build
        name: Build
        uses: docker://maven:3.8.7-openjdk-18-slim
        run: |
          set -eo pipefail
          /.mvnw packag
          echo "________ BUILD ADVISOR ________"
          echo "________ TEST ADVISOR ________"
